/* Copyright 2026 Michael Sherman
 * Copyright 1989-2025 PTC Inc.; 1984-1988 Symbolic Dynamics, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "language.h"

struct language FORTRAN_language = {
        0,
        "FORTRAN",
#ifdef apollo
        ".ftn",
#else
#ifdef vms
        ".for",
#else
#ifdef RWIN32
        ".for",
#else
        ".f",
#endif
#endif
#endif
        1, 72, 2, -1,
        "(", ",", ")", "*", "      ", "", "     & ", "",
        "C ", 2, "\n", "C", "= ",
        " .lt. "," .le. "," .eq. "," .ne. "," .ge. "," .gt. ",
            " .and. "," .or. ",".not. ",
        "d", "integer ", "real ", "double precision ", "external ", "", "",
        "\nsubroutine ", "\nfunction ", "\n", "", "", "\n", "%>", 
        "%<\nreturn\nend\n", "%<\nend\n", "call ", "", "",
        "if (%Dabs(%s) .gt. %s) %s\n",
        "if (", ") then\n%>", " %s %s) then\n%>", "%<else\n%>", "%<endif\n",
        "do %s %s=%s,%s\n%>", "do %s %s=1,%s\n%>", "%<%Bcontinue\n", "%<%Bcontinue\n%Bcontinue\n",
        "%Bcontinue\n%>", "%<if (%s .ge. 1) goto %s\n",
        "%Bif (", " %s %s) then\n%>", "goto %s\n%<endif\n",
        "%Bcontinue\n%>", "%<goto %s\n", "%<goto %s\n%Bcontinue\n",
        "goto %s\n", "%{%s%}%Bcontinue\n", "%{goto %s%}goto %s\n", "return\n", 
          "return\n",
        "","","%.0s%s",
        "","","data ","/","/\n",
        "sin","cos","abs","asin","acos","sqrt","atan2",
        LANG_STMT_UPPER|LANG_COMMON_DECL
        |LANG_LINE_COMMENTS|LANG_SEPARATE_INIT|LANG_VARDIM|LANG_COLMAJOR
        |LANG_FUNCVAL_IN_NAME },
    ADSIM_language = {
        &FORTRAN_language,
        "ADSIM", ".ads", 1, 80, 2, -1,
        "_", "_", "", "*", "    ", "", "      ", "",
        "! ", 0, "\n", "", " = ",
        " .lt. "," .le. "," .eq. "," .ne. "," .ge. "," .gt. ",
            " .and. "," .or. ",".not. ",
        "", "%{%>integer ", "real ", "double precision ", "external ", "", "",
        "\nsubroutine ", "\nfunction ", "\n", "", "", "\n", "%>", 
        "%<", "%<", "", "", "",
        "",
        "if ", " then\n%>", " %s %s then\n%>", "%<else\n%>", "%<endif\n",
        "", "", "", "",
        "", "",
        "", "", "",
        "", "", "",
        "", "", "", "return\n", "return\n",
        "","","%.0s%s",
        "","","data ","/","/\n",
        "sin","cos","abs","asin","acos","sqrt","atan2",
        LANG_COMMON_DECL|LANG_LINE_COMMENTS|LANG_SEPARATE_INIT
        |LANG_FUNCVAL_IN_NAME },
    ADSIM_language_decl = {
        0,
        "ADSIMd", ".ads", 1, 80, 2, -1,
        "(", ",", ")", "*", "!   ", "", "!     ", "",
        "! ", 0, "\n", "", " = ",
        " .lt. "," .le. "," .eq. "," .ne. "," .ge. "," .gt. ",
            " .and. "," .or. ",".not. ",
        "", "%{%>integer ", "real ", "double precision ", "external ", "", "",
        "\nsubroutine ", "\nfunction ", "\n", "", "", "\n", "%>", 
        "%<", "%<", "", "", "",
        "",
        "if ", " then\n%>", " %s %s then\n%>", "%<else\n%>", "%<endif\n",
        "", "", "", "",
        "", "",
        "", "", "",
        "", "", "",
        "", "", "", "return\n", "return\n",
        "","","%.0s%s",
        "","","data ","/","/\n",
        "sin","cos","abs","asin","acos","sqrt","atan2",
        LANG_COMMON_DECL|LANG_LINE_COMMENTS|LANG_SEPARATE_INIT
        |LANG_FUNCVAL_IN_NAME },
    KRC_language = {
        &ADSIM_language,
        "K&R C", ".c", 0, 80, 4, 0,
        "[", "][", "]", "", "", "", "  ", ";",
        "/* ", -3, " */\n",
        "", " = ",
        " < "," <= "," == "," != "," >= "," > "," && "," || ","!",
        "", "int ", "float ", "double ", "int ", "&", "*",
        "\nvoid ", "\n", "{\n", ";\n", "%>", "%<\n", "%>", 
        "%<}\n", "%<}\n", "", "()", "()",
        "if (fabs(%s) > %s)\n%>%s\n%<",
        "if (", ") {\n%>", " %s %s) {\n%>", "%<} else {%>\n", "%<}\n",
        "%:Ls%:Vsfor (%V = %s; %V <= %s; %V++) {\n%>", 
            "%:Ls%:Vsfor (%V = 0; %V < %s; %V++) {\n%>", "%<}\n", "%<}\n",
        "do {\n%>", "%<} while (%s >= 0);\n",
        "while (", " %s %s) {\n%>", "%<}\n",
        "for (;;) {\n%>", "%<}\n", "%<}\n",
        "break;\n", "%s: ;\n", "goto %s;\n", "return %s;\n", "return;\n", 
        "\ntypedef struct {\n%>", "%<} %@A%s;\n", "%@A%s.%s_",
        " = {\n%>","%<};\n","/* "," */ ",",\n",
        "sin","cos","fabs","asin","acos","sqrt","atan2",
        LANG_C_FAMILY },
    ANSIC_language = {
        &KRC_language,
        "ANSI C", ".c", 0, 80, 4, 0,
        "[", "][", "]", "", "", "", "  ", ";",
        "/* ", -3, " */\n",
        "", " = ",
        " < "," <= "," == "," != "," >= "," > "," && "," || ","!",
        "", "int ", "float ", "double ", "int ", "&", "*",
        "\nvoid ", "\n", "{\n", ";\n", "%>", "%<\n", "%>", 
        "%<}\n", "%<}\n", "", "(void)", "()",
        "if (fabs(%s) > %s)\n%>%s\n%<",
        "if (", ") {\n%>", " %s %s) {\n%>", "%<} else {%>\n", "%<}\n",
        "%:Ls%:Vsfor (%V = %s; %V <= %s; %V++) {\n%>", 
            "%:Ls%:Vsfor (%V = 0; %V < %s; %V++) {\n%>", "%<}\n", "%<}\n",
        "do {\n%>", "%<} while (%s >= 0);\n",
        "while (", " %s %s) {\n%>", "%<}\n",
        "for (;;) {\n%>", "%<}\n", "%<}\n",
        "break;\n", "%s: ;\n", "goto %s;\n", "return %s;\n", "return;\n", 
        "\ntypedef struct {\n%>", "%<} %@A%s;\n", "%@A%s.%s_",
        " = {\n%>","%<};\n","/* "," */ ",",\n",
        "sin","cos","fabs","asin","acos","sqrt","atan2",
        LANG_C_FAMILY|LANG_DECL_IN_ARGLIST },
    Cpp_language = {
        &ANSIC_language,
        "C++", ".cpp", 0, 80, 4, 0,
        "[", "][", "]", "", "", "", "  ", ";",
        "// ", -3, "\n",
        "", " = ",
        " < "," <= "," == "," != "," >= "," > "," && "," || ","!",
        "", "int ", "float ", "double ", "int ", "&", "*",
        "\nvoid ", "\n", "{\n", ";\n", "%>", "%<\n", "%>", 
        "%<}\n", "%<}\n", "", "()", "()",
        "if (fabs(%s) > %s)\n%>%s\n%<",
        "if (", ") {\n%>", " %s %s) {\n%>", "%<} else {%>\n", "%<}\n",
        "%:Ls%:Vsfor (%V = %s; %V <= %s; %V++) {\n%>", 
            "%:Ls%:Vsfor (%V = 0; %V < %s; %V++) {\n%>", "%<}\n", "%<}\n",
        "do {\n%>", "%<} while (%s >= 0);\n",
        "while (", " %s %s) {\n%>", "%<}\n",
        "for (;;) {\n%>", "%<}\n", "%<}\n",
        "break;\n", "%s: ;\n", "goto %s;\n", "return %s;\n", "return;\n", 
        "\ntypedef struct {\n%>", "%<} %@A%s;\n", "%@A%s.%s_",
        " = {\n%>","%<};\n","/* "," */ ",",\n",
        "sin","cos","fabs","asin","acos","sqrt","atan2",
        LANG_C_FAMILY|LANG_DECL_IN_ARGLIST|LANG_LINE_COMMENTS },
    Pascal_language = {
        &Cpp_language,
        "Pascal",
#ifdef apollo
        ".pas",
#else
#ifdef vms
        ".pas",
#else
        ".p",
#endif
#endif
        1, 80, 4, 0,
        "[", ",", "]", "", "", "", "  ", ";",
        "{ ", -2, " }\n", "", " := ",
        " < "," <= "," = "," <> "," >= "," > "," and "," or ","not ",
        "", "integer", "shortreal", "real", "procedure", "", "",
        "\nprocedure ", "\nfunction ", ";\n", "; forward;\n", "var\n%>", "%<", "begin\n%>",
        "%<end;\n", "%<end;\n", "", "", "",
        "if abs(%s) > %s then\n%>%s\n%<",
        "if ", " then begin\n%>", " %s %s then begin\n%>", "%<end else begin\n%>", "%<end;\n",
        "%:Lsfor %s := %s to %s do begin\n%>", 
            "%:Lsfor %s := 1 to %s do begin\n%>", "%<end;\n", "%<end;\n%s:\n",
        "repeat\n%>", "%<until %s < 1;\n",
        "while ", " %s %s do begin\n%>", "%<end;\n",
        "while true do begin\n%>", "%<end;\n", "%<end;\n%s:\n",
        "goto %s;\n", "%{%s%}%s:\n", "%{goto %s%}goto %s;\n", "return;\n",
          "return;\n",
        "\ntype %@A%s = record\n%>", "end;\n%<", "%@A%s.%s",
        " := \n%>",";%<\n","{ "," } ",",\n",
        "sin","cos","abs","asin","acos","sqrt","atan2",
        LANG_DECL2|LANG_DECL_IN_ARGLIST|LANG_FUNCVAL_IN_NAME },
    Ada_language = {
        &Pascal_language,
        "Ada", ".ada", 1, 80, 4, 0,
        "(", ",", ")", "<>", "", "", "  ", ";",
        "-- ", -3, "\n", "", " := ",
        " < "," <= "," = "," /= "," >= "," > "," and then "," or else ","not ",
        "", "integer", "short_float", "long_float", "procedure", "", "",
        "\nprocedure ", "\nfunction ", " is\n\n", ";\n", "%>", "%<", "begin\n%>", 
        "%<end;\n", "%<end;\n", "", "", "",
        "if abs %s > %s then\n%>%s\n%<end if;\n",
        "if ", " then\n%>", " %s %s then\n%>", "%<else\n%>", "%<end if;\n",
        "%:Lsfor %s in %s..%s loop\n%>", 
            "%:Lsfor %s in 1..%s loop\n%>", "%<end loop;\n", "%<end loop;\n",
        "loop\n%>", "exit when %s < 1;\n%<end loop;\n",
        "loop exit when ", "%s %s;\n%>", "%<end loop;\n",
        "loop\n%>", "%<end loop;\n", "%<end loop;\n",
        "exit;\n", "<<%s>>\n", "goto %s;\n", "return %s;\n", "return;\n", 
        "\ntype %@A%s = record\n%>", "end;\n%<", "%@A%s.%s",
        " := \n%>",";%<\n","{ "," } ",",\n",
        "sin","cos","abs","asin","acos","sqrt","atan2",
        LANG_DECL2|LANG_DECL_IN_ARGLIST|LANG_LINE_COMMENTS|LANG_VARDIM },
    Text_language = {        /* used for output to user */
        0,
        "Text", "", 0, 0, 4, 0,
        "", "", "", "", "", "", "", "",
        "", 0, "\n", "", "",
        "","","","","","","","","",
        "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", 
        "", "", "", "", "",
        "", 
        "", "", "", "", "",
        "", "", "", "",
        "", "", 
        "", "", "", 
        "", "", "", 
        "", "", "", "", "",
        "", "", "",
        "", "", "", "", "",
        "", "", "", "", "", "", "",
        0 },
    *Lang;
